DEPARTMENT_FIELDS = {
    1: {  # Contabilidade
        "name": "Contabilidade",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data de Competência",
                "type": "date",
                "required": True,
                "description": "Data do lançamento contábil (DD/MM/AAAA)",
            },
            {
                "key": "data_lancamento",
                "label": "Data de Lançamento",
                "type": "date",
                "required": False,
                "description": "Data em que o lançamento foi registrado",
            },
            {
                "key": "descricao",
                "label": "Descrição",
                "type": "string",
                "required": False,
                "description": "Histórico do lançamento",
            },
            {
                "key": "codigo_reduzido",
                "label": "Código da Conta",
                "type": "string",
                "required": True,
                "description": "Código reduzido do plano de contas (busca na tabela)",
            },
            {
                "key": "codigo_centro_custo",
                "label": "Centro de Custo",
                "type": "string",
                "required": False,
                "description": "Código do centro de custo (busca na tabela)",
            },
            {
                "key": "debito",
                "label": "Valor Débito",
                "type": "float",
                "required": False,
                "description": "Valor de débito (R$)",
            },
            {
                "key": "credito",
                "label": "Valor Crédito",
                "type": "float",
                "required": False,
                "description": "Valor de crédito (R$)",
            },
            {
                "key": "valor",
                "label": "Valor Total",
                "type": "float",
                "required": False,
                "description": "Valor total do lançamento (R$)",
            },
        ],
    },
    2: {  # Financeiro
        "name": "Financeiro",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data",
                "type": "date",
                "required": True,
                "description": "Data da movimentação financeira",
            },
            {
                "key": "descricao",
                "label": "Descrição",
                "type": "string",
                "required": False,
                "description": "Descrição da movimentação",
            },
            {
                "key": "cliente_cnpj",
                "label": "CNPJ/CPF Cliente",
                "type": "string",
                "required": False,
                "description": "CNPJ ou CPF do cliente/fornecedor",
            },
            {
                "key": "codigo_centro_custo",
                "label": "Centro de Custo",
                "type": "string",
                "required": False,
                "description": "Código do centro de custo",
            },
            {
                "key": "codigo_conta",
                "label": "Conta Contábil",
                "type": "string",
                "required": True,
                "description": "Código da conta no plano de contas",
            },
            {
                "key": "valor",
                "label": "Valor",
                "type": "float",
                "required": True,
                "description": "Valor da movimentação (R$)",
            },
            {
                "key": "tipo",
                "label": "Tipo (Receita/Despesa)",
                "type": "string",
                "required": False,
                "description": "R=Receita, D=Despesa",
            },
        ],
    },
    3: {  # Vendas
        "name": "Vendas",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data da Venda",
                "type": "date",
                "required": True,
                "description": "Data em que a venda foi realizada",
            },
            {
                "key": "cliente_cnpj",
                "label": "CNPJ/CPF do Cliente",
                "type": "string",
                "required": True,
                "description": "CNPJ ou CPF do cliente (busca na tabela)",
            },
            {
                "key": "produto_codigo",
                "label": "Código do Produto",
                "type": "string",
                "required": True,
                "description": "Código do produto vendido (busca na tabela)",
            },
            {
                "key": "fazenda_codigo",
                "label": "Código da Fazenda",
                "type": "string",
                "required": False,
                "description": "Código da fazenda de origem (busca na tabela)",
            },
            {
                "key": "armazem_codigo",
                "label": "Código do Armazém",
                "type": "string",
                "required": False,
                "description": "Código do armazém de destino",
            },
            {
                "key": "safra",
                "label": "Safra",
                "type": "string",
                "required": False,
                "description": "Código da safra (ex: 23/24)",
            },
            {
                "key": "quantidade_sc",
                "label": "Quantidade (Sacas)",
                "type": "float",
                "required": True,
                "description": "Quantidade em sacas de 60kg",
            },
            {
                "key": "quantidade_ton",
                "label": "Quantidade (Toneladas)",
                "type": "float",
                "required": False,
                "description": "Quantidade em toneladas",
            },
            {
                "key": "valor_total",
                "label": "Valor Total (R$)",
                "type": "float",
                "required": True,
                "description": "Valor total da venda",
            },
            {
                "key": "valor_unitario",
                "label": "Preço Unitário (R$/sc)",
                "type": "float",
                "required": False,
                "description": "Preço por saca",
            },
        ],
    },
    4: {  # Compras
        "name": "Compras",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data da Compra",
                "type": "date",
                "required": True,
                "description": "Data da compra",
            },
            {
                "key": "fornecedor_cnpj",
                "label": "CNPJ do Fornecedor",
                "type": "string",
                "required": True,
                "description": "CNPJ do fornecedor (busca na tabela)",
            },
            {
                "key": "produto_codigo",
                "label": "Código do Produto",
                "type": "string",
                "required": True,
                "description": "Código do produto comprado",
            },
            {
                "key": "quantidade_sc",
                "label": "Quantidade (Sacas)",
                "type": "float",
                "required": True,
                "description": "Quantidade em sacas",
            },
            {
                "key": "valor_total",
                "label": "Valor Total (R$)",
                "type": "float",
                "required": True,
                "description": "Valor total da compra",
            },
            {
                "key": "safra",
                "label": "Safra",
                "type": "string",
                "required": False,
                "description": "Safra relacionada",
            },
            {
                "key": "descricao",
                "label": "Descrição",
                "type": "string",
                "required": False,
                "description": "Descrição da compra",
            },
        ],
    },
    5: {  # Produção
        "name": "Produção",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data",
                "type": "date",
                "required": True,
                "description": "Data do registro de produção",
            },
            {
                "key": "fazenda_codigo",
                "label": "Código da Fazenda",
                "type": "string",
                "required": True,
                "description": "Fazenda de produção",
            },
            {
                "key": "produto_codigo",
                "label": "Código do Produto",
                "type": "string",
                "required": True,
                "description": "Produto colhido",
            },
            {
                "key": "safra",
                "label": "Safra",
                "type": "string",
                "required": True,
                "description": "Safra",
            },
            {
                "key": "area_plantada",
                "label": "Área Plantada (ha)",
                "type": "float",
                "required": False,
                "description": "Área plantada em hectares",
            },
            {
                "key": "quantidade_sc",
                "label": "Colheita (Sacas)",
                "type": "float",
                "required": True,
                "description": "Quantidade colhida em sacas",
            },
            {
                "key": "produtividade",
                "label": "Produtividade (sc/ha)",
                "type": "float",
                "required": False,
                "description": "Produtividade em sacas por hectare",
            },
            {
                "key": "custo_total",
                "label": "Custo Total (R$)",
                "type": "float",
                "required": False,
                "description": "Custo total da produção",
            },
        ],
    },
    6: {  # Logística
        "name": "Logística",
        "fields": [
            {
                "key": "data_competencia",
                "label": "Data",
                "type": "date",
                "required": True,
                "description": "Data do frete/transporte",
            },
            {
                "key": "fazenda_codigo",
                "label": "Código da Fazenda",
                "type": "string",
                "required": False,
                "description": "Fazenda de origem",
            },
            {
                "key": "armazem_codigo",
                "label": "Código do Armazém",
                "type": "string",
                "required": False,
                "description": "Armazém de destino",
            },
            {
                "key": "produto_codigo",
                "label": "Código do Produto",
                "type": "string",
                "required": False,
                "description": "Produto transportado",
            },
            {
                "key": "quantidade_sc",
                "label": "Quantidade (Sacas)",
                "type": "float",
                "required": True,
                "description": "Quantidade transportada",
            },
            {
                "key": "distancia_km",
                "label": "Distância (km)",
                "type": "float",
                "required": False,
                "description": "Distância percorrida",
            },
            {
                "key": "valor_frete",
                "label": "Valor do Frete (R$)",
                "type": "float",
                "required": True,
                "description": "Valor total do frete",
            },
            {
                "key": "transportadora",
                "label": "Transportadora",
                "type": "string",
                "required": False,
                "description": "Nome da transportadora",
            },
        ],
    },
}
